[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x77a4b96f2120>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1f8b0e2f-2723-4876-b984-b78dda5cb7cc
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x77a4b96f19d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1f8b0e2f-2723-4876-b984-b78dda5cb7cc
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x77a4b96f3ef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1f8b0e2f-2723-4876-b984-b78dda5cb7cc